#! /usr/bin/env ruby
# Usage: ev logins
# Summary: shows you all our general use logins
# Help: Talk to sengming.tan@evercondo.com for the master password.
# You will require gpg to decrypt this. Try `brew install gpg`.
#
# Adding more passwords
# 1. cd ev
# 2. ev logins decrypt-and-edit
# 3. ev logins encrypt
# 4. git push

require File.expand_path("../../lib/ev", __FILE__)

raise 'Please get GPG. i.e. `brew install gpg`' unless File.which('gpg')

if ARGV[0] == 'decrypt-and-edit'
  system 'gpg --quiet data/logins.gpg'
  exec 'vi data/logins'
elsif ARGV[0] == 'encrypt'
  puts 'Please re-use the same Master Password'
  system 'gpg -c --cipher-algo AES256 data/logins'
  system 'git commit -m "updates logins" data/logins.gpg'
else
  system "gpg --quiet -o - #{File.join Ev.root, 'data', 'logins.gpg'}"
end